name: Docker Image Push
description: Push Docker images to ECR (AWS), GAR (Google Artifact Registry), Buildkite Package Registries, Artifactory, or Namespace Private Container Registry
author: https://github.com/buildkite-plugins
requirements:
  - bash
  - docker
configuration:
  properties:
    provider:
      type: string
      enum: [ecr, gar, buildkite, artifactory, namespace]
      description: Registry provider type
    image:
      type: string
      description: Docker image name to push
    tag:
      type: string
      description: Tag for the image
      default: "latest"
    ecr:
      type: object
      description: ECR-specific configuration
      properties:
        region:
          type: string
          description: AWS region for ECR registry
        account-id:
          type: string
          description: AWS account ID
        registry-url:
          type: string
          description: ECR registry URL
      additionalProperties: false
    gar:
      type: object
      description: GAR-specific configuration
      properties:
        project:
          type: string
          description: Google Cloud project ID
        region:
          type: string
          description: GAR region (e.g. "us") or full GAR host (e.g. "europe-west10-docker.pkg.dev")
          default: "us"
        repository:
          type: string
          description: Artifact Registry repository name (defaults to the image name when omitted)
      additionalProperties: false
    buildkite:
      type: object
      description: Buildkite Packages Container Registry configuration
      properties:
        org-slug:
          type: string
          description: Buildkite organization slug
        registry-slug:
          type: string
          description: Container registry slug (defaults to the image name when omitted)
        auth-method:
          type: string
          enum: [api-token, oidc]
          description: Authentication method
          default: "api-token"
        api-token:
          type: string
          description: Buildkite API token with Read Packages and Write Packages scopes (required when auth-method is api-token)
      additionalProperties: false
    artifactory:
      type: object
      description: Artifactory Docker Registry configuration
      properties:
        registry-url:
          type: string
          description: Artifactory registry URL (e.g., "myjfroginstance.jfrog.io")
        username:
          type: string
          description: Username (typically email address) for Artifactory authentication
        identity-token:
          type: string
          description: Artifactory identity token for authentication
        repository:
          type: string
          description: Artifactory repository name (defaults to the image name when omitted)
      required:
        - registry-url
        - username
        - identity-token
      additionalProperties: false
    namespace:
      type: object
      description: Namespace registry configuration
      properties:
        tenant-id:
          type: string
          description: Namespace tenant/workspace ID
        registry:
          type: string
          description: Namespace registry host (defaults to "nscr.io")
        nsc-binary:
          type: string
          description: Path to Namespace CLI binary (defaults to /root/.ns/bin/nsc)
        auth-method:
          type: string
          enum: [buildkite-oidc, aws-cognito]
          default: buildkite-oidc
        buildkite-oidc:
          type: object
          description: Settings for buildkite-oidc auth method
          properties:
            audience:
              type: string
              description: Custom OIDC audience (defaults to "federation.namespaceapis.com")
          additionalProperties: false
        aws-cognito:
          type: object
          description: Settings for aws-cognito auth method
          properties:
            region:
              type: string
              description: AWS region for Cognito federation
            identity-pool:
              type: string
              description: AWS Cognito identity pool GUID
          additionalProperties: false
      additionalProperties: false
    verbose:
      type: boolean
      description: Enable verbose logging and debug mode (set -x)
      default: false
  required:
    - provider
    - image
  additionalProperties: false
