steps:
  - label: ":shell: Tests"
    plugins:
      - plugin-tester#v4.2.0:
          folders:
            - tests

  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v2.1.0:
          id: template

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/**
            - lib/**